#define T_FN                               1
#define T_ID                               2
#define T_LEFT_BRACE                       3
#define T_RIGHT_BRACE                      4
#define T_LEFT_PARENTHESIS                 5
#define T_RIGHT_PARENTHESIS                6
#define T_ON                               7
#define T_COMMA                            8
#define T_EQUALS                           9
#define T_SEMICOLON                       10
#define T_IF                              11
#define T_INT_V                           12
#define T_FLOAT_V                         13
#define T_STRING_V                        14
#define T_TRUE                            15
#define T_FALSE                           16
#define T_LEFT_BRACKET                    17
#define T_RIGHT_BRACKET                   18
#define T_DOT                             19
#define T_INCREMENT                       20
#define T_DECREMENT                       21
#define T_POW                             22
#define T_MINUS                           23
#define T_BITWISE_INVERT                  24
#define T_INVERT                          25
#define T_SIZEOF                          26
#define T_MULTIPLY                        27
#define T_DIVIDE                          28
#define T_REMAINDER                       29
#define T_PLUS                            30
#define T_BITWISE_SHIFT_LEFT              31
#define T_BITWISE_SHIFT_RIGHT             32
#define T_LESS_THAN                       33
#define T_GREATER_THAN                    34
#define T_LESS_THAN_OR_EQUALS             35
#define T_GREATER_THAN_OR_EQUALS          36
#define T_NOT_EQUALS                      37
#define T_BITWISE_AND                     38
#define T_BITWISE_XOR                     39
#define T_BITWISE_OR                      40
#define T_AND                             41
#define T_OR                              42
#define T_QUESTION_MARK                   43
#define T_COLON                           44
#define T_ASSIGN                          45
#define T_ASSIGN_MULTIPLY                 46
#define T_ASSIGN_DIVIDE                   47
#define T_ASSIGN_REMAINDER                48
#define T_ASSIGN_PLUS                     49
#define T_ASSIGN_MINUS                    50
#define T_ASSIGN_BITWISE_SHIFT_LEFT       51
#define T_ASSIGN_BITWISE_SHIFT_RIGHT      52
#define T_ASSIGN_BITWISE_AND              53
#define T_ASSIGN_BITWISE_XOR              54
#define T_ASSIGN_BITWISE_OR               55
