#define T_ID                               1
#define T_COMMA                            2
#define T_EQUALS                           3
#define T_FN                               4
#define T_LEFT_BRACE                       5
#define T_RIGHT_BRACE                      6
#define T_LEFT_PARENTHESIS                 7
#define T_RIGHT_PARENTHESIS                8
#define T_ON                               9
#define T_SEMICOLON                       10
#define T_IF                              11
#define T_INT_V                           12
#define T_FLOAT_V                         13
#define T_STRING_V                        14
#define T_TRUE                            15
#define T_FALSE                           16
#define T_LEFT_BRACKET                    17
#define T_RIGHT_BRACKET                   18
#define T_DOT                             19
#define T_POW                             20
#define T_MINUS                           21
#define T_BITWISE_INVERT                  22
#define T_INVERT                          23
#define T_MULTIPLY                        24
#define T_DIVIDE                          25
#define T_REMAINDER                       26
#define T_PLUS                            27
#define T_BITWISE_SHIFT_LEFT              28
#define T_BITWISE_SHIFT_RIGHT             29
#define T_LESS_THAN                       30
#define T_GREATER_THAN                    31
#define T_LESS_THAN_OR_EQUALS             32
#define T_GREATER_THAN_OR_EQUALS          33
#define T_NOT_EQUALS                      34
#define T_BITWISE_AND                     35
#define T_BITWISE_XOR                     36
#define T_BITWISE_OR                      37
#define T_AND                             38
#define T_OR                              39
#define T_QUESTION_MARK                   40
#define T_COLON                           41
#define T_ASSIGN                          42
#define T_ASSIGN_MULTIPLY                 43
#define T_ASSIGN_DIVIDE                   44
#define T_ASSIGN_REMAINDER                45
#define T_ASSIGN_PLUS                     46
#define T_ASSIGN_MINUS                    47
#define T_ASSIGN_BITWISE_SHIFT_LEFT       48
#define T_ASSIGN_BITWISE_SHIFT_RIGHT      49
#define T_ASSIGN_BITWISE_AND              50
#define T_ASSIGN_BITWISE_XOR              51
#define T_ASSIGN_BITWISE_OR               52
